### ISSUE TITLE
Bulkdataupdater endless keeps fetchin records 

### ISSUE THREAD

**Issue by jellevervloessem** [rappen/BulkDataUpdater#101]
I tried tu update multiple accounts.
I have 35000 account, useing the fetchxmlbuilder I get the same amount.
Using the BulkDataUpdate, it keeps fetching 600.000 accounts, tehn I killed the XrmToolbox.

Restarting the BulkDataUpdater keeps fetching the previous malicious request. So I stopped using XRMToolBox for now, I don't want to hit my API limit...

---
- Deployment: Online
- DB Version: 9.2.20122.144
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2021.1.44
- Tool Version: 1.2020.12.5

**Comment by rappen** [comment]
Aouch.
First, if you delete the BDU settings file for the connection you are using, it should "forget" what you did last time and not try to execute the query next time you open BDU. Howto: https://www.screencast.com/t/eDelrFkqFt
Second, if you open Edit FetchXML, does it show exactly the same query as your "verified" query in FXB?

**Comment by jellevervloessem** [comment]
Cleared the connection settings.
restarted the BDU, and the fetch is the same:
`<fetch>
  <entity name="account" />
</fetch>`

same issue, keeps retrieving records...

**Comment by rappen** [comment]
Seems like the right file was not deleted then (since I just cannot find any other reason) - could you make sure you delete all files containing "BDU" under the Settings folder and then restart XrmToolBox?

There is no default query for BDU to run, so this must have been picket up from settings somewhere...

**Comment by jellevervloessem** [comment]
OK, today it worked! I again deleted the settings file (there was only 1) but now restarted XrmToolbox. Not sure if I did last time.
All solved now! Thx!
