### ISSUE TITLE
Update with a regular expression

### ISSUE THREAD

**Issue by MscrmTools** [rappen/BulkDataUpdater#102]
For string/memo columns, it would be super nice to have the possibility to use a regular expression to transform the value

I had the problem to remove all space characters in a text field. It would have been super easy if such a feature would have existed.

---
- Deployment: Online
- DB Version: 9.2.21012.146
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2021.1.44
- Tool Version: 1.2020.12.5

**Comment by rappen** [comment]
Adding regex support could be useful!
And the regex should be applied to the current value of the column, I guess?

In the meantime, you can use the Replace feature of XRM Tokens: https://jonasr.app/xrm-tokens/#formatting

**Comment by MscrmTools** [comment]
Yes, you are correct.

Wow! I did not notice the Token formatting features! Nice one!

**Comment by rappen** [comment]
Source is available in the [Rappen.XTB.Helper](https://github.com/rappen/Rappen.XTB.Helper/blob/main/XrmSubstituter.cs) repo 😊

**Comment by rappen** [comment]
Long time later...
Is there something we need, or does the Calculate work good enough?
