### ISSUE TITLE
[Enhancement] Copy data from one field to another

### ISSUE THREAD

**Issue by rwilson504** [rappen/BulkDataUpdater#108]
Reason for Request:
I have found situations where i need to copy data from on field to another on an entity.  For example I recently had a situation where i was required to store the previous value of a lookup.  The requirement came after i was already in production so after deploying my solution i needed to update the new previous value lookup to the current value. 

Request:
Add a mechanism to allow for copying data from one field to another.  

Potential Design:
- On the Update tab of the tool add a "Copy" option to the radio buttons.
- When user select an attribute the secondary dropdown list populates with the attributes on that entity which match the data type.   The secondary dropdown should take into account the following
-- Filter the originating attribute from the list.
-- Choice (Based on Global Choice Sets), Only show fields using the same global choice sets.
-- Choice (local options), Show all fields that are local choices and allow user to map choices if needed.
-- Text, if the max text size metadata is different let the user know that the data may be truncated.
-- Lookups, Only show fields that reference the same entity type.

Example:  Allow the user to select a TwoOption field from the selected attribute and then allow the user to select another TwoOption attribute field where the data would be copied to.

![image](https://user-images.githubusercontent.com/7444929/108639654-aee8aa80-7463-11eb-81a7-9fd0c9e97d79.png)

**Comment by rappen** [comment]
Interesting!
I will look at this.
