### ISSUE TITLE
Cannot update a lookup column with "Calculate" 

### ISSUE THREAD

**Issue by sbetzin** [rappen/BulkDataUpdater#116]
I am am trying to update a lookup column on an entity. to achieve this I have added an import column with contains the guid. (through an dataflow).
Now I want to transfer the "gg_impmitglied" guid to the "gg_mitglied". with this approach:

![image](https://user-images.githubusercontent.com/1607849/111866695-96d74e80-896f-11eb-90d0-8805d41bb113.png)

The update runs without errors but the target column gg_mitglied stays empty...?

What I am doing wrong?

![image](https://user-images.githubusercontent.com/1607849/111866679-698aa080-896f-11eb-92fd-cfcfaa507560.png)

(the first value in the column was set manually to see the column in the list)

**Comment by rappen** [comment]
Calculate is unfortunate only writing to string columns, I'm working on it...
See #148
