### ISSUE TITLE
SetStateRequest using Update not SetState

### ISSUE THREAD

**Issue by greensweater** [rappen/BulkDataUpdater#117]
In BDUSetState.cs, method GetSetStateRequest returns UpdateRequest (line 197) which is not backwards compatible (throws errors). Suggest returning an actual SetStateRequest here which is still supported despite being deprecated, or add an option to choose request type in the SetState tab.

**Comment by rappen** [comment]
Thanks for info. (and sorry for my very late...)
Which version are you running on, of the Dynamics?

**Comment by greensweater** [comment]
I was supporting CRM 2011. I compiled my own version of your plugin in order to do the bulk setstate. I believe CRM 2015 Update 1 is when SetStateRequest was deprecated (https://himbap.com/blog/?p=1515) so earlier versions will fail, if that matters :)

**Comment by rappen** [comment]
Fixed like this:

![image](https://user-images.githubusercontent.com/2572253/126647998-ebcac3fa-9d16-4d26-ac29-eeb349926040.png)
