### ISSUE TITLE
Update money field with calculated value error 

### ISSUE THREAD

**Issue by JulieWartanian** [rappen/BulkDataUpdater#136]
I tried to update a money field with calculated value with this formula {heca_montant|<Math|-|80.00>} but got an error: Error: Substitute math text must be a valid decimal number (€800.00).

How can I resolve this in order for it to work?

![image](https://user-images.githubusercontent.com/85179790/120344581-619d9400-c302-11eb-8db2-aa0c89ec7cbf.png)

**Comment by rappen** [comment]
Hi!
For `Money` column you have to add `<value>` to be a number, instead as you see with `€800.00`.
Example: `{creditlimit|<value><Math|-|80>}`

Unfortunately this is not enough too bad....
The tool can for current version always white Calculate to string/text columns... 😫
I will start on calculate to other column types!
See #148

**Comment by rappen** [comment]
The **XRM Tokens** are now including info about raw values:
https://jonasr.app/xrm-tokens/#raw

**Comment by JulieWartanian** [comment]
Hello, 

Thank you for adding the raw values!
