### ISSUE TITLE
Changing statecode/statuscode doesn't work

### ISSUE THREAD

**Issue by rappen** [rappen/BulkDataUpdater#15]
Changing StateCode gives error:
```
Required field 'State' is missing
```

Changing StatusCode gives error:
```
2 is not a valid status code for state code [myentity].Enabled
on sdkmessageprocessingstep with Id [a guid].
```

**Comment by cint-mats** [comment]
Consequence of CRM requirement of setting both or none?

**Comment by v22arvind** [comment]
I see that its now a 'coming soon' feature and this bug suggests that earlier it was included in the list of fields that could be updated.
Can we bring back this feature till the new status change feature is completed?
