### ISSUE TITLE
Set value from another column

### ISSUE THREAD

**Issue by MscrmTools** [rappen/BulkDataUpdater#157]
It would be nice to have an additional action possibility that would be to set the value of a column from another column of the same type.
For example, I need to copy the datetime value from one column to another one.

Extra feature, allow all types to be used if destination column is a text column, since the conversion would be easy (basically, just a .ToString(), except for special types Lookup, Money and OptionSets)

**Comment by rappen** [comment]
I will sometime add any type to the XrmSubstituter in https://github.com/rappen/Rappen.XTB.Helper
One day!
If you vote this more - it might get there sooner 😉

**Comment by rappen** [comment]
Related: #108
