### ISSUE TITLE
It may be Broken ...

### ISSUE THREAD

**Issue by MoonBoyd** [rappen/BulkDataUpdater#158]
Hi Jonas,

Bulk Data Updater may be broken, it only lists views beginning with A-P.  Refreshing the views shows a repeating list of A-P

---
- Deployment: Online
- DB Version: 9.2.22023.147
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 1.2022.3.3

**Comment by rappen** [comment]
Is it about 5000 records in A-P?
Then I suggest that you work the first 5000 records, and then add a filter to the query so you exclude the already updated records.

If it fewer records than 5000 - we look for other problems...

**Comment by rappen** [comment]
Any more info?
Or should this be closed?

**Comment by rappen** [comment]
Closing now, reopen if you have more problems.
