### ISSUE TITLE
Open View doesn't list all the views

### ISSUE THREAD

**Issue by MoonBoyd** [rappen/BulkDataUpdater#161]
I'll admit that 187 views on the account entity is quite a few, but I was surprised when "Open View" would not list them all.  Even more strange, each time I clicked on the "Refresh views" button, It just added another copy of the first incomplete list.

Using latest versions of everything on latest version of chrome.

**Comment by rappen** [comment]
Hey, I see the problems if you double click (or even more "fast" clicking) the entities and views are doubling the lists. I will fix this.
![image](https://user-images.githubusercontent.com/2572253/172334732-b2c453b1-59a5-446f-872b-09511d72bbd4.png)


If you have 187 visible in Dynamics but not in BDU - I would guess that you have a few "My Views", these are not shown in BDU, only System Views.
Would you like the Personal/My Views to show too?

**Comment by MoonBoyd** [comment]
The personal views show already, just not all the public views

**Comment by rappen** [comment]
Solved finally.
