### ISSUE TITLE
Calculated MultipleOptionSet not working

### ISSUE THREAD

**Issue by Suxsem** [rappen/BulkDataUpdater#166]
Hello, thank you for the useful tool!
Unfortunately it seems that Calculated, MultipleOptionSet has not been implemented.
Any chance you could do that?
Thank you!

**Comment by rappen** [comment]
Yep, sorry, I didn't include Choices (MultipleOptionSet) in [this version](https://jonasr.app/bdu-1-2022-4/#col-types)...
A bit harder, but I will work on that "soon"...

**Comment by Suxsem** [comment]
Thank you!!

**Comment by rappen** [comment]
This feature requires that you know the numbers of the options.

Could be used like this:

![image](https://user-images.githubusercontent.com/2572253/182191001-12a65395-3a04-464d-bb77-eb5c9d68fac2.png)

The values shall be between semicolons, and only numbers.
In this case, I use with both calculated and "hard number".

Available in next release, hopefully quite soon!
