### ISSUE TITLE
Saving data, config, executes - and load these

### ISSUE THREAD

**Issue by rappen** [rappen/BulkDataUpdater#167]
### Discussed in https://github.com/rappen/BulkDataUpdater/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **@Rasmus-Petersen-RLL-Sampension** July 21, 2022</sup>
BDU would be the perfect tool to anonymize data if it was possible to save ones settings.

So generate a document containing:
* Fetch used to retrieve records.
* For Update - Attributes to be updated and Execution settings
* For Assign - The user/team to assign and Execution settings
* For Set State - The status and status reason and Execution settings
* For Delete - The Execution settings

And then of course functionality to load any previous saved settings.

Such an UPGRADE will come in extremely handy when one lives on the blessings of the EU GDPR rules and one therefore should anonymize any data in DEV and TEST environments.</div>

**Comment by Rasmus-Petersen-RLL-Sampension** [comment]
Yes, that looks perfect :-)
When released I'll be dancing in my office, while giving cheers to you Jonas.

As a Dane I must admit some Swedes are Jävla BRA ;-)
