### ISSUE TITLE
Support for Decimal fields calculated update

### ISSUE THREAD

**Issue by kozziag** [rappen/BulkDataUpdater#173]
Hello!

First of, thank you for adding support for currency in the past. 
Second, I was wondering if you could add support for Decimal Fields also.  

This is to have calculated updates on Decimal Fields.

Thanks in advance.

**Comment by rappen** [comment]
Hi @kozziag - I have tested a lot about this, it just works...
Maybe I misunderstand what you mean.
Could you add more detail about what you want to do, and when it does not work?

**Comment by rappen** [comment]
Closing this issue due to no response.
Please reopen if the issue still occurs.
