### ISSUE TITLE
SetState not works on entity type "workflow"

### ISSUE THREAD

**Issue by danielejdm** [rappen/BulkDataUpdater#178]
I had the need to deactivate business rules (workflow category=2) in bulk.
I get the following error when I try to deactivate (not for the viceversa). 
I developed a small Console-App to perform the same action, and with it I am able to activate and deactivate "workflows" (Workflows, Business Rules, etc...).
Here a snippet from my Code

![image](https://user-images.githubusercontent.com/34159960/201656798-a8123d0d-0433-4884-a46d-39b95f89fb3a.png)

I am currently working on Dynamics 365 onprem v. 9.1: it can be that the reason why it is not working for me the BDU?
Thanks for support

---
```
System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault>:
**Cannot update a published workflow definition.**
mscorlib

Server stack trace: 
   bei System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   bei System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   bei System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   bei System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   bei Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.<>c__DisplayClass40_0.<SetStateRecords>b__0(BackgroundWorker bgworker, DoWorkEventArgs workargs)
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

---
- XrmToolBox Version: 1.2022.11.59
- BulkDataUpdater Version: 1.2022.11.2
- DB Version: 9.1.10.102
- Deployment: OnPremise

**Comment by rappen** [comment]
Very very late response, sorry about that...

From next release it will be possible to update State and State Reason as well.
Although, that does not help us anyway, for the `workflow`.
I've tried both with Update in my tool and Set State, and both get a correct error message from the Dataverse, like this one:

![image](https://github.com/rappen/BulkDataUpdater/assets/2572253/77abb4bd-977d-4829-80d7-9bdbe3b190c4)

Your code is exactly like mine...

Any more clues to solve this, or should we just accept what MS says?

**Comment by rappen** [comment]
Closing this since no response. Please reopen if needed!
