### ISSUE TITLE
Unhandled exception when exiting (Error while serializing)

### ISSUE THREAD

**Issue by jdpottle** [rappen/BulkDataUpdater#190]
When using the tool to do any updates to data, like setting a lookup field value, when I try to exit the tool, I get and Unhandled Exception Error: Error while serializing: There was an error generating the XML document. If I click Continue, the error message goes away but I Bulk Data Updater is still open. If I click Quit, the full XRMToolbox closes. I can start new instances of Bulk Data Updater but I cannot close any of the open instances. I have tried uninstalling/reinstalling and even tried a full reset of my installation of XRMToolbox. Please help
[BulkDataUpdaterError.txt](https://github.com/rappen/BulkDataUpdater/files/11799044/BulkDataUpdaterError.txt)

**Comment by rappen** [comment]
Issue is confirmed.
Working on the fixes.
