### ISSUE TITLE
Ejecution in MV W10 System.OutOfMemoryException

### ISSUE THREAD

**Issue by jangelmgRGA** [rappen/BulkDataUpdater#191]
[Write any error info to resolve easier]

---
```
System.OutOfMemoryException:
Se produjo una excepción de tipo 'System.OutOfMemoryException'.
System.ServiceModel.Internals
   en System.Runtime.Fx.AllocateByteArray(Int32 size)
```

---
- XrmToolBox Version: 1.2023.6.65
- BulkDataUpdater Version: 1.2022.11.2
- DB Version: 9.2.23061.188
- Deployment: Online

**Comment by rappen** [comment]
Very late response, sorry - do you always get this issue? Or only once?
Any more info for me to try to resolve it?

**Comment by rappen** [comment]
Closing this now due to no response, please reopen if needed!
