### ISSUE TITLE
Bulk data update times out

### ISSUE THREAD

**Issue by imahdi3** [rappen/BulkDataUpdater#194]
Hi,
The following error occurs sometimes when I do bulk update to Dataverse records. The update batch size is 500 and the total records is close to 10k. Some update runs pass smoothly, and some fails during execution showing the following error:

---
```
System.Net.WebException:
The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
System
- System.Net.HttpWebRequest.GetResponse()
- System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
```

---
- XrmToolBox Version: 1.2023.6.65
- BulkDataUpdater Version: 1.2022.11.2
- DB Version: 9.2.23062.168
- Deployment: Online

**Comment by rappen** [comment]
I'll close this issue now since no response. 
Please reopen if it's still a problem!
