### ISSUE TITLE
Unhandled exception message

### ISSUE THREAD

**Issue by Jeff-Loretta** [rappen/BulkDataUpdater#201]
Hey!
I've been getting the following error message for the past few weeks and can't seem to get past it. 

Any help would be appreciated. I love the tool!
---
- Deployment: Online
- DB Version: 9.2.23083.160
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.6.65
- Tool Version: 1.2022.11.2

![image](https://github.com/rappen/BulkDataUpdater/assets/144482854/f90a5f6f-5df2-4ef6-a4e1-d0c59ddf91d9)

**Comment by rappen** [comment]
Sorry, extremely late response, but can you add me some more info about when this occurs?
Do you see it in version 1.2023.11.2 as well?

**Comment by Jeff-Loretta** [comment]
Hi Jonas,
I'm still receiving the unhandled exception error. I'm on 2023.12.68
Can't seem to get past it. Any help is appreciated. Great tool!

[image: image.png]

**Comment by rappen** [comment]
The version you sent me was the version of the XrmToolBox; I'm more interested in the version of the tool Bulk Data Updater.
Currently available version is now 1.2024.2.2.

**Comment by rappen** [comment]
Closing this issue due to no response. Please reopen if needed!
