### ISSUE TITLE
Unhandled exception Saving a BDU Job

### ISSUE THREAD

**Issue by bwmodular** [rappen/BulkDataUpdater#202]
Hi there,
when I try and save a (not very complex, only one attribute updated) job, it crashes with an unhandled exception.

The error is:
There was an error generating the XML document.

The resulting xml doc is partially formed:
![image](https://github.com/rappen/BulkDataUpdater/assets/1889586/b96d9e9e-bea3-42bf-a650-ada2822c3189)

I don't think there's anything special about this particular BDU job - I've taken a screenshot which I can share with you privately in case you want to see more details.
Thanks as ever....

**Comment by rappen** [comment]
I've not tested this (why don't I see the `ownerbusinessunit` attribute??), but I'm pretty sure it is now fixed.
Please reopen this if it's still a problem (after next release, only "days away" I hope).
