### ISSUE TITLE
Error when trying to run job

### ISSUE THREAD

**Issue by stephenzimmerman1** [rappen/BulkDataUpdater#216]
I tested this job just yesterday and all worked fine.  Nothing has changed with data or job... just tried running this morning and got this error.  Have uninstalled tool and reinstalled.  Have uninistalled XRMToolbox and reinstalled.  No dice.  Any ideas would be helpful.

---
```
System.ServiceModel.FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault>:

Bulk Data Updater

Server stack trace: 
- System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
- System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
- System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
- System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
- Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.ExecuteRequest(OrganizationRequest request, JobExecuteOptions executeoptions)
- Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.UpdateRecordsWork(BackgroundWorker bgworker, DoWorkEventArgs workargs, IEnumerable`1 includedrecords, JobExecuteOptions executeoptions)
- Cinteros.XTB.BulkDataUpdater.BulkDataUpdater.<>c__DisplayClass57_0.<UpdateRecords>b__1(BackgroundWorker bgworker, DoWorkEventArgs workargs)
- System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
- System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

---
- XrmToolBox Version: 1.2023.12.68
- BulkDataUpdater Version: 1.2024.2.2
- DB Version: 9.2.24015.202
- Deployment: Online

**Comment by stephenzimmerman1** [comment]
Additionally:  I do not think this is actually a problem with the tool... I think it's more likely a problem with the environment.  However, I submitted this just to make sure it hasn't come up before and there isn't some sort of fix.  Thanks!

**Comment by rappen** [comment]
Appreciate your issue.
Can it work now, again?

**Comment by stephenzimmerman1** [comment]
It's working now... I did something stupid.  I'm sorry I bothered you.


Steve Zimmerman

PTEMS/D365

Take2 Consulting

***@***.***

***@***.***

(501) 208-2888 (c)

________________________________
