### ISSUE TITLE
Error adding columns when no attributes in query

### ISSUE THREAD

**Issue by ovinophile** [rappen/BulkDataUpdater#231]
Using v1.2024.6.1

When "which columns to show" setting is set to "in the query" (the default) and the Fetch XML query has no attribute tags (returning all columns), an ArgumentNullException is thrown when clicking the Add button. To workaround I had to add an attribute (or use a view), then click Add in order to get to the settings and select "everything" for "which columns to show".

**Comment by rappen** [comment]
This is duplicated with #227.
Doing a query without any attributes is not recommended; see [MS Learn](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/fetchxml/reference/all-attributes?WT.mc_id=DX-MVP-5002475).

I have changed the code to accept no- or all-attributes without ugly error; see [commit](https://github.com/rappen/BulkDataUpdater/commit/fe3d4f70833a0b367121c4a3bd7810629b72792b).
This will be included in the next release.

**Comment by ovinophile** [comment]
Sorry, didn't check the closed issues. Thank you!
