### ISSUE TITLE
Object not getting disposed? Memory consumption is huge

### ISSUE THREAD

**Issue by shytikov** [rappen/BulkDataUpdater#27]
I'm using BulkDataUpdater to delete data in CRM, moving through dataset by portions of 100 records.

There are no other plugins running. And after several iterations (5-10). I see this:

![image](https://user-images.githubusercontent.com/1185905/52788764-3a9ff300-3062-11e9-9a94-769caef6a77f.png)

That could be also problems within `XTB` core, but I assume that maybe after each loop of processing we most likely need to explicitly call garbage collector to mark data as no longer needed.

**Comment by rappen** [comment]
Aouch.
Looking forward to a PR! 🤓
