### ISSUE TITLE
Condition with single space value gets trimmed to empty string

### ISSUE THREAD

**Issue by cint-mats** [rappen/BulkDataUpdater#28]
When using a condition with single space value in fetchxml, BDU trims the value to an empty string next time you open the fetchxml editor.

Example: `<condition attribute="xyz" operator="ends-with" value=" " />` is trimmed to `<condition attribute="xyz" operator="ends-with" value="" />` next time

Update: Similar behaviour in FetchXML Builder.

**Comment by cint-mats** [comment]
Looks like the culprit is in CSRichTextBoxSyntaxHighlighting.XMLViewer.Process calling CharacterEncoder.Encode which returns an empty string when the input is whitespace only. 

All is part of Cinteros.Xrm.XmlEditorUtils but not sure of how to find/update.

**Comment by rappen** [comment]
@jamesnovak Any idea if this is handled better in [that common repository we are extremely slowly building] ?

**Comment by jamesnovak** [comment]
No, it's handled the same way.  it's part of the CharacterEncoder.Encode method.  Should be an easy update to allow for spaces.  This is the issue:
            if (string.IsNullOrWhiteSpace(originalText))
            {
                return string.Empty;
            }
