### ISSUE TITLE
[Enhancement] Update Failure for Resolved Case (incient) Records

### ISSUE THREAD

**Issue by LinnZawWin** [rappen/BulkDataUpdater#78]
When the Case (incident) records with Resolved Status (statecode = 1) are updated via API, the system validation plugin throws the following error.

`Since case is resolved and read-only, only these attributes are updatable : "ownerid", "owneridyominame", "owneridtype", "owninguser", "statecode", "statuscode", "modifiedon", "modifiedby", "modifiedonbehalfby", "owningbusinessunit" , "processid". If you need to edit other fields, please reactivate the case.`

But for some reasons, updating using the Bulk Data Updater fails silently (even without "Ignore errors" option) and the status is shown as "X records updated, 0 records failed" even though the values were not updated (and the update was failed)

Steps to repro:

1. Open Bulk Data Updater tool
2. Edit FetchXML to query the resolved cases
`<fetch><entity name="incident"><attribute name="incidentid" /><filter type="and"><condition attribute="statecode" operator="eq" value="1" /></filter></entity></fetch>`
3. Make sure "Ignore errors" checkbox is unchecked.
4. Update the 'title' attribute of one selected record
5. Check if the value is updated or remains the same.

It would be great if the tool can show the number of records failed correctly.
And it would be better if the tool can remember the original statecode & statuscode, re-open the case, update the values and revert back to the original statecode & statuscode.

**Comment by rappen** [comment]
Hmmm...
It seams this is "not" a problem, since I can actually change the `title` attribute...

See before change:
![image](https://user-images.githubusercontent.com/2572253/135275283-649bafed-64eb-462c-937a-b8a224db6911.png)

See after change:
![image](https://user-images.githubusercontent.com/2572253/135275383-6a1a0d36-077b-4ef4-8dc7-45518304e9c3.png)

What do I do? 🙂

**Comment by LinnZawWin** [comment]
I guess MS has updated their backend plugin to allow updating the Resolved cases via API. I guess we no longer need this enhancement, then. 😀 Thanks for checking.
