### ISSUE TITLE
[Enhancement] Support for BypassCustomPluginExecution option

### ISSUE THREAD

**Issue by LinnZawWin** [rappen/BulkDataUpdater#79]
**When the BypassCustomPluginExecution parameter of the update request is supported by Microsoft**, it would be great to have as one of the Execution options which allows the user to Bypass Custom Plugin Execution for specific "Update records" action.

Ref: https://markcarrington.dev/2020/10/30/bypassing-cds-plugins/

**Comment by rwilson504** [comment]
This is something I could also use.  It would really speed up things when i just need to update data that doesn't affect plugins.  Additionally it would allow me to bypass all the update plugins when doing deletes which would also dramatically speed up that process.

**Comment by rappen** [comment]
I haven't read this for a while...
Any new since back after October...?
Ping @LinnZawWin @MarkMpn

**Comment by MarkMpn** [comment]
Yes, all properly released now 😅

Updated blog: https://markcarrington.dev/2021/05/27/bypassing-plugins-in-dataverse-faster-simpler-data-imports/

The core part of my SQL 4 CDS  implementation: https://github.com/MarkMpn/Sql4Cds/blob/bf144fa01879df3fb7c778d40874935247c1d3b6/MarkMpn.Sql4Cds.Engine/ExecutionPlan/BaseDmlNode.cs#L366

Also worth taking a look at the EnableAffinityCookie setting if you’re doing multi-threaded updates: https://markcarrington.dev/2021/05/26/improving-bulk-dataverse-performance-with-enableaffinitycookie/

**Comment by rappen** [comment]
Nice.
I may look at implement this!
(Jim is okey now...? 😉)

**Comment by rappen** [comment]
Ok, I'm trying to remember about this :) It's time!
@LinnZawWin and maybe @MarkMpn this feature still works? We need only a checkbox down to the right, right?
Can it be used for all requests (update, setstate, delete, assign) ? (I know, I should really read Mark's blog...)

**Comment by MarkMpn** [comment]
Yep, this should work for all requests. Simple checkbox should be perfect.
