### ISSUE TITLE
Query is done on the main thread

### ISSUE THREAD

**Issue by daryllabar** [rappen/BulkDataUpdater#99]
The query to retrieve the entities is done on the main UI thread, hanging the app

---
- Deployment: Online
- DB Version: 9.1.0.25851
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.10.41
- Tool Version: 1.2019.12.1

**Comment by rappen** [comment]
Hm. No.

https://github.com/rappen/BulkDataUpdater/blob/master/BulkDataUpdater/AppCode/BDUGeneral.cs#L215-L219

Guessing this is not what you refer to?

**Comment by daryllabar** [comment]
Figured it out.  The thread hang was on loading the grid.  It takes a minute or so to load 300k records (of just Ids) into the grid on the VM that I'm running.  When that is happening, the UI is unresponsive.  But that has to run on the UI thread, so maybe only show the first 5000 records in the grid?

**Comment by rappen** [comment]
I believe I explicitly tell it to load all pages. I guess you could prevent that by specifying `top` ?

**Comment by daryllabar** [comment]
I haven't tried, but know that if I'm trying to queue over 500k entities for deletion, it's annoying...  Maybe cap how much data it returns?  I don't know...

**Comment by rappen** [comment]
Hi @daryllabar - this is looong ago....
You know if this is still a problem? I should fix it?

**Comment by rappen** [comment]
No really solution to this issue. Closing it now, please reopen if needed!
